baseURL: "https://rouzbehani.com/" 
title: Hi I'm Ryin
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

#menu:
#    main:
#        - name: Publications
#          url: papers/
#          weight: 1
#        - name: Courses
#          url: courses/
#          weight: 2
#        - name: Data
#          url: data/
#          weight: 3 
#        - name: Projects
#          url: /
#          weight: 3

params:
    description: "Passionate about bioinformatics, health informatics, and data science—with an extra splash of love for aquariums."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ryin Rouzbehani M.S.
          subtitle: "Passionate about bioinformatics, health informatics, and data science—with an extra splash of love for aquariums."
          imageUrl: "me.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ryin
          #buttons:
          #  - name: Publications
          #    url: papers/
          #  - name: Courses
          #    url: courses/
          #  - name: Projects
          #    url: /
    socialIcons:
        - name: Email
          url: mailto:ryinrouz94@gmail.com
        - name: Projects
          url: https://public.tableau.com/views/GroundLevelFalls_5_4/UnintentionalNon-FatalFalls65?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=HtzmRIwAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/rrouz

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "RR"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
